fix: run tests before push (instead of before commit)
Running tests before push is enough imho.
Exception: We still run "secret scan" every commit.
Goal : faster `git commit` for dev speed